### ISSUE TITLE
We hope to support file downloads and the retrieval of the friends list.

### ISSUE THREAD

**Issue by HollisMeynell** [MaxOhn/rosu-v2#36]
- get friends list(api v2, need `friends.read`, [link](https://osu.ppy.sh/docs/#get-apiv2friends)): `https://osu.ppy.sh/api/v2/friends`
- download osu file(public api) : `https://osu.ppy.sh/osu/{bid}`
- download osz file, it is web api, the request needs to include the header `Cookie: osu_session={session}` and `Referer: https://osu.ppy.sh/beatmapsets/{sid}`  `https://osu.ppy.sh/beatmapsets/{sid}/download`

**Comment by HollisMeynell** [comment]
Perhaps directly downloading the .osz file isn't appropriate, but currently, no method has been found to retrieve the complete audio through the available API 😭

**Comment by MaxOhn** [comment]
> * get friends list(api v2, need `friends.read`, [link](https://osu.ppy.sh/docs/#get-apiv2friends)): `https://osu.ppy.sh/api/v2/friends`

Pretty much the only reason this one isn't added is because I haven't had a use yet myself 😄 Will require some minor restructuring for scoping but I'll try to work on it soon 👍 

Regarding `.osu` or `.osz` download, `rosu-v2` is only intended to request data from the `/api/v2/` endpoints so indeed I don't think it's appropriate to add support for those. It really is unfortunate that there's no way to get them through the regular API.

**Comment by HollisMeynell** [comment]
`/api/v2/friends`  no parameters are required, sort by name (but can not change, from [here](https://github.com/ppy/osu-web/blob/a4542e36c636de98af18a8ca061a91462ee1d028/app/Http/Controllers/FriendsController.php#L42)). 

The user's `access_token` must be provided, if the authorization scope does not include `friends.read`, it will fail. 

The returned result is a list containing the `User`, without limit, all results are returned at once (normally a person can only have 500 friends at most, except for user 'Zallius' 🤣).
```
[ {user}, {user},... ]
```

hope this will be of some help to you

**Comment by MaxOhn** [comment]
#37 and #38 now allow accessing the friend list of an authenticated user :tada: 

Not sure yet about releasing a new version for `rosu-v2` but in the meanwhile you'll be able to make use of this when importing the `lazer` branch through git. Beware, #37 introduces a small breaking change since `OsuBuilder::with_authorization` now takes an additional `Scopes` argument.
